### ISSUE TITLE
Other dependency managers

### ISSUE THREAD

**Issue by theallseingeye** [amsokol/openshift-golang-template#5]
Will you be adding other dependency managers like godep, govendor etc.

heroku has some example https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile

**Comment by amsokol** [comment]
Dear @theallseingeye ,

Will do.
Please give me couple of days.
I come back soon.

Thanks

**Comment by amsokol** [comment]
Done.
I added support for glide, godep, govendor managers support (#5).
Take latest version and enjoy )))

Thanks.

**Comment by theallseingeye** [comment]
Wow awesome :+1:

**Comment by theallseingeye** [comment]
Is github.com/constabulary/gb used often?

**Comment by amsokol** [comment]
I have never heard about it before.
Very interesting... i need to take a look at gb.
Thanks! )))

**Comment by theallseingeye** [comment]
Thanks, I just saw it in the Heroku buildpack. I'm still learning, so was just asking that's all

**Comment by amsokol** [comment]
So... `gb` looks interesting but it's too young I think.
`gb` has incompatible with `go build` project structure.
That's why it's not supported by IDE's (JetBrains, Visual Studio Code, Atom, etc.) intellisense yet as I see.
It makes coding harder for you.
My opinion if you are starting in golang you should use traditional `go build` for now.

By the way I think I add `gb` to openshift-golang-template as an experimental feature.
Thanks again )))
