### ISSUE TITLE
Please add command line parameters and external configuration files

### ISSUE THREAD

**Issue by devcodewak** [amsokol/openshift-golang-template#6]
@amsokol 
Great project, the first openshift v3 c2i deployment framework, has been deployed through the test, thanks

Most applications require command parameters or external configuration files, please add support

**example1 command line:  runtime or develop env**
APP_ARGV1=-L http2://user1:pass1@:$PORT
APP_ARGV2=-v4
……
or
APP_ARGV=-L http2://user1:pass1@:$PORT -v4

**example2 config files: runtime or develop env**
APP_CONFIGFILE1=gost.json
APP_CONFIGFILE2=host.json
……
Scripts need to copy one or more configuration files.
source GOPROJECT_CMD/
target  GOPATH/bin/

thx.

**Comment by amsokol** [comment]
Dear @devcodewak 

Great idea. 
Come back soon.

Thx

**Comment by amsokol** [comment]
Dear @devcodewak 

Done.
I have released v1.8.1-7, v1.8.2-3, v1.8.3-3 versions.
Please take a look at README.md (section 14, 15, 16).

I have only one question:
It's not `good practice` to do any work in `s2i/bin/run` script in addition to running the application.
That's why I copy/download configuration files in `s2i/bin/assemble` script.
So it means OpenShift will download configuration files only once during build process
Is it OK?

Are there some cases when it's needed to download configuration files every time app is started?
In this case I have to add downloading configuration files in `s2i/bin/run` script despite the fact that I think it's a bad idea.

Thanks

**Comment by devcodewak** [comment]
Hi, hardworking author, see commit, see docker has been upgraded, 
perfect, i take the time to test, thx

Understand that you said assemble and run script dilemma, need to choose,
Personal advice can be handled simply, the current assemble script has been met most of the scene.
A few starts each time the download configuration can be handled by the golang application itself.

I am a Chinese, a bad google translation, please forgive me :)

**Comment by amsokol** [comment]
@devcodewak 

Thanks!

Don't worry about English ))).
I'm not English native language speaker too.

Thanks
